#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/Documents/work ~/Documents/personal ~/Documents/programs ~/Documents/projects -mindepth 1 -maxdepth 1 -type d | fzf)
fi

[[ -z $selected ]] && exit 0

selected_name=$(basename "$selected" | tr . _)

if ! tmux has-session -t=$selected_name 2>/dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected" "ready-tmux; exec zsh"
fi

if [[ -n $TMUX ]]; then
    tmux switch-client -t "$selected_name"
else
    tmux attach-session -t "$selected_name"
fi

